version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
  ai-agent:
    image: <imagem-do-agente-ia> # Substitua pela imagem desejada
    ports:
      - "5000:5000"
